### ISSUE TITLE
change the information set of sections in the level.

### ISSUE THREAD

**Issue by ductuan10081992** [pritishvaidya/react-native-speedometer#4]
Hello.
I want to change the information set of sections in the level.
For example, I want to divide the cake into the following sections:
Parts 1: 13 to 18.5
Parts 2: 18.5 to 24.9
parts 3: 25 to 29.9
parts 4: 30 to 34.9
how will i do
And I want to turn off the index display and explain the index of the chart. Please teach me.
Thank you very much.

**Comment by pritishvaidya** [comment]
Do you want `13` as min value and  `34.9` as max value ? Right now what it does is based on the number of sections it divides the colors to speedometer.

**Comment by ductuan10081992** [comment]
> Do you want `13` as min value and `34.9` as max value ? Right now what it does is based on the number of sections it divides the colors to speedometer.

 I want to turn off the index display and explain the index of the chart. can you help me?

**Comment by ductuan10081992** [comment]
> Do you want `13` as min value and `34.9` as max value ? Right now what it does is based on the number of sections it divides the colors to speedometer.

If I split the parts unequally, how can I do this? 
Example:
Blue: 1 to 15
Red: 16 to 60
Purple: 61 to 90.
and I want to turn off the index display and explain the index of the chart???? please teach me.
Please help me to day. Thank you very much!!!

**Comment by ductuan10081992** [comment]
> Do you want `13` as min value and `34.9` as max value ? Right now what it does is based on the number of sections it divides the colors to speedometer.

How can I use the value as a decimal? example 18.6 or 20.9

**Comment by pritishvaidya** [comment]
The code is dependant on circle radi which is generated by splitting the labels equally across `180deg`. Therefore you can't split it unequally for now. 

The Label Name can be disabled by removing name from labels array 
`  {
          name: '',
          labelColor: '#ff2900',
          activeBarColor: '#ff2900',
        },`

Index cannot be removed for now.
I'll add the enhancement to the [TODOS](https://github.com/pritishvaidya/react-native-speedometer/blob/master/README.md#todos) and will complete them whenever I am available.

Since the speedometer works based on number of labels, it will automatically take care if the split results in decimal values.

Thanks
